spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\Users\leejihoon\Desktop\CQRE\cqre
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #콘솔에 로그를 찍음
        format_sql: true #쿼리 이쁘게 나옴

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: jangchanghun011@gmail.com
    password: wprkfrhdaud12!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  #devtools:
    #restart:
      #enabled: true

logging.level:
  org.hibernate.SQL: debug #콘솔이 아니라 로그파일로 남김
  #org.hibernate.type: trace #파라미터 까지 볼 수 있음